"use client";
import Link from "next/link";
import { useState } from "react";
import type { AgentSummary, WorkTask } from "@/lib/workspace";
import { displayTime, leaseState } from "@/lib/workspace";
import { Badge, Empty, Field, LiveStatus, Loading, Notice, PageHeading, requestJson, useAction, useLiveData } from "./shared";
type AgentData = { agents: AgentSummary[]; tasks: WorkTask[]; runs: { id: string; agentId: string; taskId: string; status: string; startedAt: string; lastHeartbeatAt?: string | null; resultSummary?: string | null }[]; writable: boolean; taskLimit: number };
export function AgentWorkspace() {
  const live = useLiveData<AgentData>("/api/workspace?view=agents"); const action = useAction();
  const [editing, setEditing] = useState<AgentSummary | null>(null);
  const toggle = (agent: AgentSummary) => void action.run(async () => { await requestJson("/api/agent-profiles", { method: "POST", body: JSON.stringify({ ...agent, enabled: !agent.enabled }) }); live.reload(); });
  return <><PageHeading eyebrow="执行协作 / 能力与责任" title="智能体中心" description="管理执行者档案、可认领范围与运行记录。登记档案不等于启动执行器，允许接单也不等于在线。" actions={<button className="os-btn os-btn-primary" disabled={!live.data?.writable} onClick={() => setEditing({ id: "", displayName: "", enabled: true, tags: [], allowedRiskLevel: "low", canWriteTasks: true, capabilities: [], canWriteWiki: false, canTouchFiles: false, canSendNotifications: false })}>＋ 登记执行者</button>} />
    {live.error && <Notice error>{live.error}</Notice>}{action.message && <Notice error>{action.message}</Notice>}
    {editing && <AgentEditor key={editing.id || "new"} agent={editing} onCancel={() => setEditing(null)} onSaved={() => { setEditing(null); live.reload(); }} />}
    {!live.data ? <Loading /> : <><div className="os-list-meta"><span>{live.data.agents.length} 个执行者 · 展示最近 {live.data.taskLimit} 项活跃关联任务</span><LiveStatus updated={live.updated} error={live.error} reload={live.reload} /></div><div className="os-card-grid">{live.data.agents.map(agent => {
      const tasks = live.data!.tasks.filter(task => task.ownerAgent === agent.id); const run = live.data!.runs.find(item => item.agentId === agent.id); const lastHeartbeat = tasks.map(task => task.lastHeartbeatAt).filter(Boolean).sort((a, b) => new Date(b!).getTime() - new Date(a!).getTime())[0] ?? run?.lastHeartbeatAt;
      return <section className="os-panel os-agent-card" key={agent.id}><header className="os-agent-header"><span className="os-avatar">{agent.displayName.slice(0, 1)}</span><div><h2>{agent.displayName}</h2><p className="os-code">{agent.id}</p></div></header><div className="os-tag-list"><Badge value={agent.enabled ? "agent_allowed" : "archived"}>{agent.enabled ? "允许接单" : "已停用"}</Badge><Badge value={agent.allowedRiskLevel} />{agent.tags.map(tag => <Badge key={tag}>{tag}</Badge>)}</div><dl className="os-detail-facts"><div><dt>关联中的任务</dt><dd>{tasks.length} 项</dd></div><div><dt>最近执行心跳</dt><dd>{displayTime(lastHeartbeat)}</dd></div><div><dt>任务写入权限</dt><dd>{agent.canWriteTasks ? "允许" : "不允许"}</dd></div><div><dt>最近运行结果</dt><dd>{run ? <Badge value={run.status} /> : "尚无记录"}</dd></div></dl>{tasks.slice(0, 2).map(task => <Link className="os-evidence-link" href={`/tasks?task=${encodeURIComponent(task.id)}`} key={task.id}>{task.title}<small>{leaseState(task)}</small></Link>)}<div className="os-actions"><Link className="os-btn" href={`/tasks?agent=${encodeURIComponent(agent.id)}&claimable=1`}>查看可认领任务</Link><button className="os-link" disabled={!live.data?.writable} onClick={() => setEditing(agent)}>配置</button><button className="os-link" disabled={!live.data?.writable || action.busy} onClick={() => toggle(agent)}>{agent.enabled ? "停用" : "启用"}</button></div></section>;
    })}</div>{!live.data.agents.length && <div className="os-panel"><Empty title="尚未登记执行者">先创建能力档案，再在系统管理页配置后台执行器。</Empty></div>}
    <section className="os-panel" style={{ marginTop: 24 }}><header className="os-panel-head"><div><h2>最近执行批次</h2><p>批次状态和成果需要分别核对，运行结束不自动代表验收通过。</p></div><Link className="os-link" href="/reviews">进入复核 ↗</Link></header><div className="os-table-wrap"><table className="os-table"><thead><tr><th>执行者</th><th>运行状态</th><th>开始时间</th><th>相关任务</th></tr></thead><tbody>{live.data.runs.map(run => <tr key={run.id}><td>{live.data!.agents.find(agent => agent.id === run.agentId)?.displayName ?? run.agentId}</td><td><Badge value={run.status} /></td><td>{displayTime(run.startedAt)}</td><td><Link className="os-link" href={`/tasks?task=${encodeURIComponent(run.taskId)}`}>查看任务与成果 ↗</Link></td></tr>)}</tbody></table></div>{!live.data.runs.length && <Empty title="暂无执行批次" />}</section></>}
  </>;
}
function AgentEditor({ agent, onCancel, onSaved }: { agent: AgentSummary; onCancel: () => void; onSaved: () => void }) {
  const action = useAction();
  return <section className="os-panel os-form-panel"><header className="os-panel-head"><h2>{agent.id ? "配置执行者" : "登记执行者"}</h2><button className="os-link" onClick={onCancel}>取消</button></header><form className="os-panel-body" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(async () => { const id = String(form.get("id") ?? "").trim(); const displayName = String(form.get("name") ?? "").trim(); if (!id || !displayName) throw new Error("请填写执行者标识和名称。"); await requestJson("/api/agent-profiles", { method: "POST", body: JSON.stringify({ ...agent, id, displayName, tags: String(form.get("tags") ?? "").split(/[,，]/).map(value => value.trim()).filter(Boolean), capabilities: String(form.get("capabilities") ?? "").split(/[,，]/).map(value => value.trim()).filter(Boolean), allowedRiskLevel: String(form.get("risk")), canWriteTasks: form.get("canWriteTasks") === "on", canWriteWiki: form.get("canWriteWiki") === "on", canTouchFiles: form.get("canTouchFiles") === "on", canSendNotifications: form.get("canSendNotifications") === "on" }) }); onSaved(); }); }}><div className="os-form-grid"><Field title="执行者标识 *"><input name="id" defaultValue={agent.id} readOnly={Boolean(agent.id)} required maxLength={100} pattern="[A-Za-z0-9_-]+" placeholder="例如 docs-worker-01" /></Field><Field title="中文名称 *"><input name="name" defaultValue={agent.displayName} required maxLength={100} placeholder="例如 文档整理执行者" /></Field><Field title="匹配标签"><input name="tags" defaultValue={agent.tags.join(", ")} maxLength={500} placeholder="多个标签用逗号分开" /></Field><Field title="允许风险等级"><select name="risk" defaultValue={agent.allowedRiskLevel}><option value="low">仅低风险</option><option value="medium">低风险与中风险</option><option value="high">档案允许高风险，自动领取仍禁止高风险</option></select></Field><div className="os-form-wide"><Field title="能力说明"><input name="capabilities" defaultValue={agent.capabilities?.join(", ")} maxLength={1000} placeholder="用于说明能力，不代替执行器的工具权限" /></Field></div>{[["canWriteTasks", "允许任务写入", agent.canWriteTasks], ["canWriteWiki", "知识写入能力标记", agent.canWriteWiki], ["canTouchFiles", "文件操作能力标记", agent.canTouchFiles], ["canSendNotifications", "通知能力标记", agent.canSendNotifications]].map(([name, text, checked]) => <label className="os-toggle-label" style={{ marginBottom: 14 }} key={String(name)}><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)} />{String(text)}</label>)}</div><Notice>能力说明和知识／文件／通知标记用于登记，不会自动授予或隔离真实工具权限。执行器的文件目录、联网范围与凭证必须单独限制。</Notice>{action.message && <Notice error>{action.message}</Notice>}<div className="os-actions"><button className="os-btn os-btn-primary" disabled={action.busy}>{action.busy ? "正在保存…" : "保存配置"}</button><button type="button" className="os-btn" onClick={onCancel}>取消</button></div></form></section>;
}
