"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { displayTime, taskStage } from "@/lib/workspace";
import type { KnowledgeCatalog, KnowledgeMeta, KnowledgeNote, KnowledgeResponse } from "@/lib/knowledge-workspace";
import { Badge, Empty, EvidenceLink, Field, Loading, Notice, PageHeading, Pagination, requestJson, useAction, useLiveData } from "./shared";
import { Markdown } from "./Markdown";
import { TaskForm } from "./TaskForm";

type Initial = { q?: string; path?: string; revision?: string };
export function KnowledgeWorkspace({ initial = {} }: { initial?: Initial }) {
  const [q, setQ] = useState(initial.q ?? "");
  const [filter, setFilter] = useState({ space: "", book: "", chapter: "", status: "" });
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(initial.path ?? "");
  const [revision, setRevision] = useState(initial.revision ?? "");
  const [editing, setEditing] = useState(false); const [creating, setCreating] = useState(false);
  const [newTask, setNewTask] = useState(false); const [message, setMessage] = useState("");
  const catalog = useLiveData<KnowledgeCatalog>(`/api/workspace/knowledge?${new URLSearchParams({ q, ...filter, page: String(page) })}`, 0);
  const detail = useLiveData<KnowledgeResponse>(selected ? `/api/workspace/knowledge?${new URLSearchParams({ path: selected, revision })}` : null, 0);
  const projects = useLiveData<{ projects: { id: string; name: string }[] }>(newTask ? "/api/workspace?view=projects" : null, 0);
  const note = detail.data?.note.path === selected ? detail.data.note : null;
  const choose = (path: string, rev = "") => { if (editing && !window.confirm("离开后未保存的修改会丢失，确认离开？")) return false; setSelected(path); setRevision(rev); setEditing(false); setCreating(false); setNewTask(false); setMessage(""); return true; };
  useEffect(() => { const params = new URLSearchParams(); if (q) params.set("q", q); if (selected) params.set("path", selected); if (revision) params.set("revision", revision); window.history.replaceState(null, "", `/wiki?${params}`); }, [q, selected, revision]);
  const saved = (value: KnowledgeNote, indexed: boolean) => { setSelected(value.path); setRevision(""); setEditing(false); setCreating(false); setMessage(indexed ? "知识页面已保存，历史版本已保留。" : "正文已保存，但索引重建失败。请检查知识服务，不要重复创建。" ); catalog.reload(); detail.reload(); };
  return <><PageHeading eyebrow="知识管理 / 手册与依据" title="知识手册" description="按空间、手册和章节组织知识。保留原始来源、修改版本，以及引用这份知识的任务。" actions={<><button className="os-btn" onClick={() => { catalog.reload(); detail.reload(); }}>刷新</button><button className="os-btn os-btn-primary" disabled={!catalog.data?.writable} onClick={() => { if (editing && !window.confirm("放弃未保存的修改？")) return; setCreating(true); setEditing(false); }}>＋ 新建知识页面</button></>} />
    {catalog.error && <Notice error>{catalog.error}</Notice>}{message && <Notice>{message}</Notice>}
    {creating ? <ManualEditor onCancel={() => setCreating(false)} onSaved={saved} /> : <>
      {newTask && note && <TaskForm projects={projects.data?.projects ?? []} source={{ title: note.title, path: note.path, revision: note.revision, url: `${window.location.origin}/wiki?path=${encodeURIComponent(note.path)}&revision=${note.revision}` }} onCancel={() => setNewTask(false)} onCreated={id => { setNewTask(false); detail.reload(); setMessage("已按当前手册版本创建任务。"); window.location.assign(`/tasks?task=${encodeURIComponent(id)}`); }} />}
      <div className="os-manual-layout"><aside className="os-panel os-manual-sidebar"><div className="os-manual-search"><input type="search" value={q} aria-label="搜索知识正文与标题" placeholder="搜索手册、正文和标签…" onChange={e => { if (!choose("")) return; setQ(e.target.value); setPage(1); }} /></div><div className="os-manual-tree"><button className={!filter.space ? "is-selected" : ""} onClick={() => { if (!choose("")) return; setFilter({ space: "", book: "", chapter: "", status: "" }); setPage(1); }}>▤ 全部知识<small>资料、手册与执行依据</small></button>
        {catalog.data && [...new Set(catalog.data.tree.map(item => item.space))].map(space => <details key={space} open><summary>{space}</summary>{[...new Set(catalog.data!.tree.filter(item => item.space === space).map(item => item.book))].map(book => <details key={book} open><summary>{book}</summary>{catalog.data!.tree.filter(item => item.space === space && item.book === book).map(item => <button key={item.chapter} className={filter.space === space && filter.book === book && filter.chapter === item.chapter ? "is-selected" : ""} onClick={() => { if (!choose("")) return; setFilter(old => ({ ...old, space, book, chapter: item.chapter })); setPage(1); }}><span>└ {item.chapter}</span><small>{item.count} 篇页面</small></button>)}</details>)}</details>)}
      </div></aside><div className="os-stack">{!selected && <section className="os-panel"><div className="os-panel-head"><div><h2>{filter.book || "知识页面"}</h2><p>{filter.space ? `${filter.space} / ${filter.chapter}` : "选择一篇页面，在工作台内阅读和维护。"}</p></div><select className="os-btn" aria-label="按发布状态筛选知识" value={filter.status} onChange={e => { setFilter(old => ({ ...old, status: e.target.value })); setPage(1); }}><option value="">全部状态</option><option value="draft">草稿</option><option value="published">已发布</option><option value="deprecated">已停用</option></select></div>
        {!catalog.data ? catalog.error ? <Empty title="知识服务未连接">请检查系统管理页的连接状态，以及知识服务是否使用新版入口。</Empty> : <Loading /> : catalog.data.notes.length ? <div className="os-note-list">{catalog.data.notes.map(item => <button key={item.path} className={`os-note-entry${selected === item.path ? " is-selected" : ""}`} onClick={() => choose(item.path)}><div><strong>{item.title}</strong><Badge value={item.status} /></div><p>{item.excerpt || "尚无摘要"}</p><small>{item.space} / {item.book} / {item.chapter}</small></button>)}</div> : <Empty title="没有符合条件的知识页面">调整搜索或分类，也可以创建一份新的操作手册。</Empty>}
        {catalog.data && <div style={{ padding: "0 20px 18px" }}><Pagination page={catalog.data.page} pageSize={catalog.data.pageSize} total={catalog.data.total} onPage={setPage} /></div>}
      </section>}
      {selected && <section className="os-panel"><header className="os-panel-head"><button type="button" className="os-btn" onClick={() => choose("")}>← 返回知识目录</button><span className="os-inline-note">正文与版本化执行依据</span></header>{detail.error && <Notice error>{detail.error}</Notice>}{!note ? detail.error ? <Empty title="这份知识暂时无法读取">历史版本缺失时不会自动替换为最新版。</Empty> : <Loading /> : editing ? <ManualEditor key={`${note.path}:${note.revision}`} note={note} onCancel={() => setEditing(false)} onSaved={saved} /> : <article className="os-manual-article"><div className="os-meta"><Badge value={String(note.frontmatter.status || "draft")} /><Badge value={String(note.frontmatter.confidence || "speculative")} />{note.historical && <Badge value="waiting">历史版本 · 只读</Badge>}</div><h1>{note.title}</h1><div className="os-article-meta"><span>维护人：{String(note.frontmatter.owner || "尚未指定")}</span><span>更新：{displayTime(String(note.frontmatter.updated || note.frontmatter.created || ""))}</span><span>版本：{note.revision.slice(0, 12)}</span><span>资料级别：{({ internal: "内部", private: "私密", public: "公开" } as Record<string, string>)[String(note.frontmatter.sensitivity)] ?? "尚未标注"}</span></div>
        {note.historical && <Notice>你正在查看本次任务引用的历史内容，不是最新手册。<button className="os-link" onClick={() => choose(note.path)}>阅读最新版</button></Notice>}
        {note.frontmatter.valid_until && new Date(String(note.frontmatter.valid_until)).getTime() < new Date(detail.updated || 0).getTime() && <Notice>这份知识已超过复核期限。执行前请确认内容仍然适用。</Notice>}
        <div className="os-actions" style={{ margin: "0 0 24px" }}><button className="os-btn" disabled={!detail.data?.writable || note.historical} onClick={() => setEditing(true)}>编辑页面</button><button className="os-btn os-btn-primary" disabled={!detail.data?.writable} onClick={() => setNewTask(true)}>按此版本创建任务</button><select className="os-btn" aria-label="选择历史版本" value={note.historical ? note.revision : ""} onChange={e => choose(note.path, e.target.value)}><option value="">当前版本</option>{note.history.filter(item => item.revision !== note.currentRevision).map(item => <option value={item.revision} key={item.revision}>{displayTime(item.savedAt)} · {item.revision.slice(0, 8)}</option>)}</select></div>
        <Markdown content={note.content} />
        {typeof note.frontmatter.source_url === "string" && <div className="os-manual-related"><h2>原始来源</h2><EvidenceLink url={note.frontmatter.source_url} /></div>}
        <div className="os-manual-related"><h2>引用这份知识的任务</h2>{detail.data?.tasks.length ? detail.data.tasks.map(task => <Link className="os-evidence-link" href={`/tasks?task=${encodeURIComponent(task.id)}`} key={task.id}>{task.title}<Badge value={taskStage(task)} /></Link>) : <p className="os-inline-note">暂未找到绑定此页面的任务。创建任务时会记录路径与执行依据版本。</p>}</div><details className="os-manual-related"><summary>页面标识与技术信息</summary><p className="os-code">稳定编号：{note.id}<br />路径：{note.path}<br />内容版本：{note.revision}</p></details>
      </article>}</section>}
      </div></div></>}
  </>;
}
function ManualEditor({ note, onCancel, onSaved }: { note?: KnowledgeNote; onCancel: () => void; onSaved: (note: KnowledgeNote, indexed: boolean) => void }) {
  const action = useAction(); const [requestId] = useState(() => crypto.randomUUID()); const metadata: KnowledgeMeta = note?.frontmatter ?? {};
  return <section className="os-panel os-form-panel"><header className="os-panel-head"><div><h2>{note ? "编辑知识页面" : "新建知识页面"}</h2><p>保存时检查内容版本，不会静默覆盖他人的修改。</p></div><button className="os-link" onClick={onCancel}>取消</button></header><form className="os-panel-body" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(async () => {
    const fields = Object.fromEntries(["space", "book", "chapter", "owner", "status", "confidence", "sensitivity", "valid_until", "source_url"].map(key => [key, String(form.get(key) ?? "").trim()]));
    const result = await requestJson<{ note: KnowledgeNote; indexed: boolean }>("/api/workspace/knowledge", { method: "POST", body: JSON.stringify({ path: note?.path, expectedRevision: note?.revision, requestId: note ? undefined : requestId, title: String(form.get("title") ?? "").trim(), content: String(form.get("content") ?? ""), metadata: fields, tags: String(form.get("tags") ?? "").split(/[,，]/).map(tag => tag.trim()).filter(Boolean) }) }); onSaved(result.note, result.indexed);
  }); }}><Field title="页面标题 *"><input name="title" required maxLength={200} defaultValue={note?.title ?? ""} /></Field><div className="os-form-grid">{[["space", "知识空间", "内部知识"], ["book", "所属手册", "工作手册"], ["chapter", "所在章节", "操作指南"], ["owner", "维护人", ""]].map(([key, title, fallback]) => <Field title={title} key={key}><input name={key} defaultValue={String(metadata[key] ?? fallback)} maxLength={160} /></Field>)}<Field title="发布状态"><select name="status" defaultValue={String(metadata.status || "draft")}><option value="draft">草稿</option><option value="published">已发布</option><option value="deprecated">已停用</option></select></Field><Field title="可信程度"><select name="confidence" defaultValue={String(metadata.confidence || "speculative")}><option value="speculative">待证实</option><option value="inferred">推断</option><option value="verified">已核验</option></select></Field><Field title="资料级别"><select name="sensitivity" defaultValue={String(metadata.sensitivity || "internal")}><option value="internal">内部资料</option><option value="private">私密资料</option><option value="public">可公开资料</option></select></Field><Field title="复核到期日期"><input name="valid_until" type="date" defaultValue={String(metadata.valid_until || "").slice(0, 10)} /></Field><Field title="标签"><input name="tags" defaultValue={Array.isArray(metadata.tags) ? metadata.tags.join(", ") : ""} placeholder="多个标签以逗号分开" /></Field><Field title="原始来源地址"><input name="source_url" defaultValue={String(metadata.source_url || "")} placeholder="保留可追溯的来源" maxLength={500} /></Field></div><Field title="正文 *"><textarea name="content" required rows={18} style={{ minHeight: 340, fontFamily: "ui-monospace, monospace" }} defaultValue={note?.content ?? "## 适用范围\n\n说明适用于哪些场景。\n\n## 前置条件\n\n- 需要的输入、权限与资源。\n\n## 操作步骤\n\n1. 第一项可以执行的动作。\n\n## 验收标准\n\n- 如何验证结果，以及需要保留哪些证据。\n\n## 异常处理与回滚\n\n记录失败时如何安全停止或恢复。\n"} /></Field><Notice>“已发布”“已核验”是维护人的明确标注，不是系统自动验证结果。资料级别用于记录分发要求，不能替代账号和网络权限隔离。</Notice>{action.message && <Notice error>{action.message}</Notice>}<div className="os-actions"><button className="os-btn os-btn-primary" disabled={action.busy}>{action.busy ? "正在保存…" : "保存页面与版本"}</button><button className="os-btn" type="button" onClick={onCancel}>取消</button></div></form></section>;
}
