"use client";
import Link from "next/link";
import { useState } from "react";
import { Badge, Empty, Field, Loading, Notice, PageHeading, requestJson, useAction, useLiveData } from "./shared";
type Project = { id: string; name: string; goal?: string | null; currentFocus?: string | null; status: string; priority: string; _count: { tasks: number } };
type ProjectResponse = { projects: Project[]; counts: { projectId: string | null; status: string; _count: { _all: number } }[]; writable: boolean };
export function ProjectWorkspace() {
  const live = useLiveData<ProjectResponse>("/api/workspace?view=projects");
  const [creating, setCreating] = useState(false); const [q, setQ] = useState(""); const action = useAction();
  return <><PageHeading eyebrow="项目协作 / 目标与交付" title="项目进度" description="把项目目标拆成可认领、可验收的任务。完成比例仅按未归档任务数量计算。" actions={<button className="os-btn os-btn-primary" disabled={!live.data?.writable} onClick={() => setCreating(true)}>＋ 新建项目</button>} />{live.error && <Notice error>{live.error}</Notice>}
    {creating && <section className="os-panel os-form-panel"><div className="os-panel-head"><h2>新建项目</h2><button className="os-link" onClick={() => setCreating(false)}>取消</button></div><form className="os-panel-body" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(async () => { await requestJson("/api/projects", { method: "POST", body: JSON.stringify({ name: String(form.get("name")).trim(), goal: String(form.get("goal")), currentFocus: String(form.get("focus")), status: "active", priority: "P2" }) }); setCreating(false); live.reload(); }); }}><div className="os-form-grid"><Field title="项目名称 *"><input name="name" required maxLength={150} /></Field><Field title="当前重点"><input name="focus" maxLength={500} /></Field><div className="os-form-wide"><Field title="项目目标"><textarea name="goal" maxLength={5000} /></Field></div></div>{action.message && <Notice error>{action.message}</Notice>}<button className="os-btn os-btn-primary" disabled={action.busy}>创建项目</button></form></section>}
    <div className="os-toolbar"><input type="search" aria-label="搜索项目" placeholder="搜索项目名称与目标…" value={q} onChange={e => setQ(e.target.value)} /><button className="os-btn" onClick={live.reload}>刷新</button></div>
    {!live.data ? <Loading /> : <div className="os-card-grid">{live.data.projects.filter(project => `${project.name} ${project.goal ?? ""}`.toLowerCase().includes(q.toLowerCase())).map(project => {
      const counts = live.data!.counts.filter(item => item.projectId === project.id && item.status !== "archived"); const total = counts.reduce((sum, item) => sum + item._count._all, 0); const done = counts.find(item => item.status === "done")?._count._all ?? 0; const blocked = counts.find(item => item.status === "blocked")?._count._all ?? 0;
      return <section className="os-panel os-project-card" key={project.id}><div className="os-meta"><Badge value={project.status} /><Badge value={project.priority} /></div><h2>{project.name}</h2><p>{project.goal || "尚未记录项目目标。"}</p><div className="os-inline-note">当前重点：{project.currentFocus || "请先明确下一项工作"}</div><div className="os-progress" role="progressbar" aria-label={`${project.name}任务完成数量`} aria-valuemin={0} aria-valuemax={total || 1} aria-valuenow={done}><span style={{ width: `${total ? done / total * 100 : 0}%` }} /></div><div className="os-project-foot"><span>{total ? `${done} / ${total} 项任务完成` : "尚未拆分任务"}</span><span>{blocked ? `${blocked} 项阻塞` : "无阻塞任务"}</span></div><div className="os-actions"><Link className="os-btn" href={`/tasks?project=${encodeURIComponent(project.id)}`}>查看任务 ↗</Link><Link className="os-link" href={`/wiki?q=${encodeURIComponent(project.name)}`}>查找相关知识</Link></div></section>;
    })}</div>}{live.data && !live.data.projects.length && <div className="os-panel"><Empty title="还没有项目">先建立目标，再为项目添加可以独立验收的任务。</Empty></div>}
  </>;
}
