"use client";
import { Badge, LiveStatus, Loading, Notice, PageHeading, useLiveData } from "./shared";
type SystemData = { database: boolean; wiki: { ok: boolean; notes: number }; writable: boolean; configured: { read: boolean; write: boolean; wikiRead: boolean; wikiWrite: boolean; agentCredentials: boolean } };
export function SystemWorkspace() {
  const live = useLiveData<SystemData>("/api/workspace?view=system", 30000); const data = live.data;
  return <><PageHeading eyebrow="系统管理 / 运行与接入" title="系统管理" description="检查服务连接、访问权限与执行器接入。这里只展示配置是否存在，不返回密钥内容。" actions={<button className="os-btn" onClick={live.reload}>重新检查</button>} />{live.error && <Notice error>{live.error}</Notice>}{!data ? <Loading /> : <>
    <div className="os-columns"><section className="os-panel"><header className="os-panel-head"><h2>服务与访问边界</h2></header><div className="os-panel-body">{[{ name: "任务数据库", ok: data.database, text: "任务、认领、执行批次和验收记录的主数据源。" }, { name: "知识服务", ok: data.wiki.ok, text: data.wiki.ok ? `当前可访问 ${data.wiki.notes} 篇知识页面。` : "检查知识服务、容器网络或读取凭证。" }, { name: "任务读取凭证", ok: data.configured.read, text: "只读访问和写入访问应使用不同凭证。" }, { name: "任务管理凭证", ok: data.configured.write, text: "管理凭证不得分发给普通执行者。" }, { name: "知识读取凭证", ok: data.configured.wikiRead, text: "仅由服务端访问知识接口，不放进浏览器脚本。" }, { name: "知识写入凭证", ok: data.configured.wikiWrite, text: "保护知识更新入口，修改前核对版本。" }, { name: "独立执行者凭证", ok: data.configured.agentCredentials, text: "使用第二版接入接口绑定执行者身份与角色。" }].map(item => <div className="os-check-row" key={item.name}><div>{item.name}<small>{item.text}</small></div><Badge value={item.ok ? "done" : "waiting"}>{item.ok ? "可用 / 已配置" : "需要检查"}</Badge></div>)}<Notice>配置存在不代表安全审核通过。局域网也需要身份验证、访问限制和可恢复的备份。</Notice><p className="os-inline-note">当前会话：{data.writable ? "管理访问" : "只读访问"}。页面状态每 30 秒检查一次。</p></div></section>
    <section className="os-panel"><header className="os-panel-head"><h2>执行器接入流程</h2></header><div className="os-panel-body os-help"><h3>一、登记执行者</h3><p>在智能体中心配置标识、标签与允许风险。每个进程使用独立的执行者标识，不共享同一个运行身份。</p><h3>二、配置后台执行器</h3><p>管理凭证只用于管理。普通执行器使用独立凭证，通过接口领取任务；关闭网页不应停止后台执行。</p><pre>领取任务 → 取得执行批次 → 读取上下文\n执行与心跳 → 提交证据 → 独立复核\n\n接口入口：/api/agent-v2\n工作台数据：/api/workspace\n知识入口：/api/workspace/knowledge</pre><h3>三、验证完整流程</h3><p>先用低风险测试任务检查认领、心跳、提交、返工和验收。不要用生产部署、付款或公开发布动作测试自动化。</p><h3>四、检查失败恢复</h3><p>租约过期后先确认旧执行器是否停止。任务记录的接管不等于外部命令已经停止，不应直接重复有副作用的操作。</p></div></section></div>
    <section className="os-panel" style={{ marginTop: 22 }}><header className="os-panel-head"><h2>局域网运行清单</h2></header><div className="os-panel-body os-help"><p>统一内部访问入口；使用受信任的 HTTPS 反向代理；数据库只开放在容器内部网络；替换所有演示凭证；明确允许提供给外部模型的资料范围。</p><p>备份应同时覆盖任务数据库、知识目录、附件和部署配置，并实际进行还原测试。不要将真实任务、内网地址、密钥或生产知识上传到公开仓库。</p><p>详细部署与验收步骤见仓库中文手册 <code>docs/CHINESE_WORKSPACE.md</code>。本页面不执行部署、删除、还原或重启操作。</p></div></section><div style={{ marginTop: 20 }}><LiveStatus updated={live.updated} error={live.error} reload={live.reload} /></div>
  </>}</>;
}
