"use client";
import { useState } from "react";
import { Field, Notice, requestJson, useAction } from "./shared";
export function TaskForm({ projects, onCreated, onCancel, source }: { projects: { id: string; name: string }[]; onCreated: (id: string) => void; onCancel: () => void; source?: { title: string; path: string; revision?: string; url?: string } }) {
  const [auto, setAuto] = useState(false);
  const action = useAction();
  return <section className="os-panel os-form-panel"><div className="os-panel-head"><div><h2>{source ? "从知识手册创建任务" : "新建任务"}</h2><p>目标、下一步与验收标准缺一不可。</p></div><button className="os-link" onClick={onCancel}>取消</button></div><form className="os-panel-body" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void action.run(async () => {
    const title = String(form.get("title") ?? "").trim(); const nextAction = String(form.get("nextAction") ?? "").trim(); const definitionOfDone = String(form.get("definitionOfDone") ?? "").trim();
    if (!title || !nextAction || !definitionOfDone) throw new Error("请填写任务标题、下一步和验收标准。");
    const response = await requestJson<{ task: { id: string } }>("/api/workspace/actions", { method: "POST", body: JSON.stringify({ action: "create", payload: { title, nextAction, definitionOfDone, description: String(form.get("description") ?? ""), priority: String(form.get("priority") ?? "P2"), status: "todo", executionMode: auto ? "agent_allowed" : "manual", riskLevel: "low", agentTags: String(form.get("tags") ?? "").split(/[,，]/).map(s => s.trim()).filter(Boolean), projectId: String(form.get("project") ?? "") || undefined, wikiLinks: source ? [{ noteTitle: source.title, notePath: source.path, noteUrl: source.url, sourceType: "manual" }] : [] } }) });
    onCreated(response.task.id);
  }); }}>
    <div className="os-form-grid"><div className="os-form-wide"><Field title="任务标题 *"><input name="title" required maxLength={200} placeholder="用一句话说明需要交付什么" defaultValue={source ? `按《${source.title}》执行` : ""} /></Field></div><Field title="所属项目"><select name="project"><option value="">暂不归属项目</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></Field><Field title="优先级"><select name="priority" defaultValue="P2"><option value="P0">紧急</option><option value="P1">重要</option><option value="P2">普通</option><option value="P3">低优先级</option></select></Field><div className="os-form-wide"><Field title="背景与依据"><textarea name="description" maxLength={12000} defaultValue={source ? `参考手册：《${source.title}》\n路径：${source.path}\n执行依据版本：${source.revision ?? "未记录版本，执行前需要确认"}` : ""} placeholder="说明为什么做，以及需要参考什么" /></Field></div><Field title="下一步 *"><textarea name="nextAction" required maxLength={5000} placeholder="写出可以开始执行的具体动作" /></Field><Field title="验收标准 *"><textarea name="definitionOfDone" required maxLength={5000} placeholder="例如：提交修改记录、通过测试，并附上验证结果" /></Field><Field title="执行者标签"><input name="tags" placeholder="例如：文档, 前端, 测试" maxLength={300} /></Field><Field title="自动执行授权"><span><input type="checkbox" checked={auto} onChange={e => setAuto(e.target.checked)} />允许符合权限的智能体认领此低风险任务</span></Field></div>
    {auto && <Notice>自动认领只适用于低风险工作。部署、付款、公开发布等操作仍应另行审批；认领后不会自动通过验收。</Notice>}{action.message && <Notice error>{action.message}</Notice>}<div className="os-actions"><button className="os-btn os-btn-primary" disabled={action.busy}>{action.busy ? "正在创建…" : "创建任务"}</button><button type="button" className="os-btn" onClick={onCancel}>取消</button></div>
  </form></section>;
}
